export const LOG_EVENTS = {
  AUTH: {
    LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
    LOGIN_FAILED: "AUTH_LOGIN_FAILED",
    REGISTER_FAILED: "AUTH_REGISTER_FAILED",
    LOGOUT_FAILED: "AUTH_LOGOUT_FAILED",
    AUTHENTICATION: {
      failed: "AUTH_REQUIRED_FAILED",
      success: "AUTH_SUCCESS",
    },
  },
  CART: {
    ADD_ITEM_FAILED: "CART_ADD_ITEM_FAILED",
    ADD_ITEM_SUCCESS: "CART_ADD_ITEM_SUCCESS",
    REMOVE_ITEM: "CART_REMOVE_ITEM_FAILED",
    TRANSACTION_ERROR: "CART_TX_ERROR",
  },
};
