export const LOG_EVENTS = {
  AUTH: {
    success: {
      LOGIN: "AUTH_LOGIN_SUCCESS",
      REGISTER: "AUTH_REGISTER_SUCCESS",
      AUTHENTICATION: "AUTH_SUCCESS",
      MERGE_CART: "AUTH_MERGE_CART_SUCCESS",
    },
    failed: {
      LOGIN: "AUTH_LOGIN_FAILED",
      REGISTER: "AUTH_REGISTER_FAILED",
      AUTHENTICATION: "AUTH_FAILED",
      LOGOUT: "AUTH_LOGOUT_FAILED",

      MERGE_CART: "AUTH_MERGE_CART_FAILED",
    },
  },
  CART: {
    ADD_ITEM_FAILED: "CART_ADD_ITEM_FAILED",
    ADD_ITEM_SUCCESS: "CART_ADD_ITEM_SUCCESS",
    REMOVE_ITEM: "CART_REMOVE_ITEM_FAILED",
    TRANSACTION_ERROR: "CART_TX_ERROR",
  },
  ORDER: {
    success: {
      CREATE: "ORDER_CREATED_SUCCESS",
      CHECKOUT: "ORDER_CHECKOUT_SUCCESS",
      ATTACH_ORDER: "ORDER_ATTACH_TO_USER_SUCCESS",
    },
    failed: {
      CHECKOUT: "ORDER_CHECKOUT_FAILED",
      ATTACH_ORDER: "ORDER_ATTACH_TO_USER_FAILED",
    },
  },
  PAYMENT: {
    failed: {
      CREATE: "PAYMENT_CREATE_FAILED",
    },
    success: {
      CREATE: "PAYMENT_CREATE_SUCCESS",
    },
  },
};
